Implemented handling for remote targets
dorsal-lab/lttng-utils pull request #1
Opened 2024-06-07 16:34 UTC by matthiasb85

Hi,
I like to use lttng on embedded linux targets, that usually don't provide any python interpreter. Also, analyzing the traces later is much more convenient , when done on a more powerful device. As a result I added some functionality to handle remote targets and executed the lttng commands via ssh.
It's far from perfect, but in case you are interested, we can use this PR for discussion.

2024-06-07 19:42 UTC, arfio commented
Hi, thank you very much for your contribution. I will take a more in depth look next week but it looks good !

2024-06-12 16:20 UTC, arfio requested changes
I think the change is great for introducing this feature.
However I wonder if you considered any other approach like https://lttng.org/docs/v2.13/#doc-sending-trace-data-over-the-network which uses lttng-relayd to stream events out of the remote system where you are running the trace session. That would eliminate the need of scp-ing the traces out.

Also, what happens when you lose the connection temporarily ? I think this issue might be important to discuss because we might want to use an external library as it would facilitate error handling with network issues.

2024-06-12 16:20 UTC, arfio commented on README.md
> +  --private-key PRIV_KEY Private ssh key for remote target connection
The remote folder setting is missing from the documentation ?

2024-06-12 16:20 UTC, arfio commented on lttng-record-trace
> +            cmd_stub(["rm", "-rf", out], False, cmd_env)
I would much prefer if something else was used to remove the folder as any error specifying the folder will result in everything being deleted.

2024-06-13 06:10 UTC, matthiasb85 commented on README.md
> +  --private-key PRIV_KEY Private ssh key for remote target connection
Done :-)

2024-06-13 06:12 UTC, matthiasb85 commented on lttng-record-trace
> +            cmd_stub(["rm", "-rf", out], False, cmd_env)
What about, adding an additional CLI flag like:
`
--remote-clean-up      Will remove REMOTE_FOLDER and its entire content. Use with caution!
`

2024-06-13 12:02 UTC, matthiasb85 commented
> I think the change is great for introducing this feature. However I wonder if you considered any other approach like https://lttng.org/docs/v2.13/#doc-sending-trace-data-over-the-network which uses lttng-relayd to stream events out of the remote system where you are running the trace session. That would eliminate the need of scp-ing the traces out.
> 
> Also, what happens when you lose the connection temporarily ? I think this issue might be important to discuss because we might want to use an external library as it would facilitate error handling with network issues.

The reason why I decided to not use lttng-relayd was, that I wanted to be able to also collect traces from other tools in the same trace folder. E.g:

`lttng-record-trace --remote root@192.168.7.2 --password linux uftrace --demangle=full -d /tmp/tracing/uftrace record my_fancy_program`

2024-06-14 13:20 UTC, arfio commented on lttng-record-trace
> +            cmd_stub(["rm", "-rf", out], False, cmd_env)
This would be a good change, one other thing would be to exclude "/" and just using "-r".

2024-06-17 15:05 UTC, arfio commented
Looks good ! Thank you for the improvements you have made, I am sure it will help other people !

2024-06-17 15:05 UTC, merged